### ISSUE TITLE
Spectra reverts to default "Villarrica" on processing DOAS

### ISSUE THREAD

**Issue by tpering** [twVolc/PyCamPermanent#116]
Select spectra etc:
![image](https://github.com/twVolc/PyCamPermanent/assets/7857899/61cc68e5-b5ab-487b-ae12-546faf8aa30d)

Click OK:

![image](https://github.com/twVolc/PyCamPermanent/assets/7857899/7c4749ef-a859-446e-8063-c685ee3e6586)

Something unusual going on?

![image](https://github.com/twVolc/PyCamPermanent/assets/7857899/69385926-f67e-48c6-833a-75daed65ca8f)

**Comment by twVolc** [comment]
I think this is just an error in the messages rather than it not working. the message jumps back to the old file then to what you've set so the final result should be that it's using the spectra directory requested. I remember seeing this when I fixed the previous bug related to it and deciding it wasn't causing any issues, it just looks a little confusing when readin the messages. I think it was more hassle than it was worth to fix the mesages so I just left it for now. I'll keep this open but remove the priority label as I'm pretty sure the processing under the hood works as we want (can be checked by looking for hot pixels in the dakr spectra - they change when loaidng in a new dark spectra folder relative to the default).

**Comment by ubdbra001** [comment]
What's happening here more specifically is that:
1. When the settings window is opened it will print the current value for the Dark spectra directory. I assume that this was from a fresh start, so that would be whatever is in the default config file (`.\pycam\tests\test_data\test_spectra\`)
2. Then when you press okay it will update the value for the Dark spectra directory, and then print the updated value.

As Tom said it'll be a bit of a pain to stop this behaviour as both parts are accessing the same function, and the way it is structured it's not easy to tell this function to only print the value in the second case.
