### ISSUE TITLE
Add functionality for copying default settings file for user

### ISSUE THREAD

**Issue by ubdbra001** [twVolc/PyCamPermanent#18]
Need to have some functionality that allows users to copy the defult settings to a local place and then load that into PyCam

**Comment by twVolc** [comment]
Just to add that as we discussed this would be really useful for being able to continue development but not getting merge conflicts (that I'm still totally useless at resolving) when I'm also using the software to process data - I typically change the defaults so I can speed up processing by loading all my data in on start-up. But I know seem to have all sorts of different version of `processing_setting_defaults.txt` in different places on my git branches. If there's a way of having the standard defaults in the conf directory, which we can update if we ever add more options but which generally won't change, and then just have an option to link to different text files outside of the scope of the git repo this would be really useful. Hopefully this makes sense, and isn't just a representation of my lack of git knowledge...

**Comment by ubdbra001** [comment]
No, this makes perfect sense. I was thinking about his yesterday, and I think it would be worth adding the option to load a config into the library (have a function that loads the config in and a corresponding button in the GUI), but also save the current config.
Possibly even have a function/flag that tells pycam to automatically save the config with the proccessed data, that way if you share data anyone else can see the settings you used to proccess it, and repeat it.

**Comment by twVolc** [comment]
Yes I just came here to say this - once we've processed some data at the moment it saves a `processing_settings.txt` file in the "Processed_x" directory within the data sequence folder. But this file isn't comprehensive - i.e. it doesn't exactly replicate the `processing_setting_defaults.txt` file that can be used on start-up to load in every setting we need to replicate that processing procedure exactly. We probably want to move to adding absolutely all of the information into the `processing_settings.txt` so that that could then be used as the start-up configuration file in the future. This will take a bit of thought to identify all of the settings within `processing_setting_defaults.txt` and see how to draw them into a file at the end of processing.

**Comment by tpering** [comment]
Just to add to this, it would be nice to have volcano specific load-outs, so it is rapid to switch between the settings for each volcano, i.e., ld lookup grids, clear/dark images, registration etc., also links to issue #39 automatically loading the young and old ica lines.

**Comment by ubdbra001** [comment]
Starting to look at this issue, and spent yesterday creating an overview of where the different settings come from (in an excel sheet [here](https://docs.google.com/spreadsheets/d/1hwQofjTIiIAO1J0i_2rT4X0tUCwSM70TpzEp9MzsqRc/edit?usp=sharing)) in an attempt to make sure I know where changes will have an impact for each config file.
@twVolc could you have a look and just make sure it looks roughly correct and that I haven't missed anything?

**Comment by twVolc** [comment]
I started something very similar the other day after our chat too! Although it's more specific to the processing_settings_default.txt keys, so hopefully it will still be useful to you. Haven't quite finished it yet as I got distracted by moving offices sorry... but I can try to finish it this afternoon.

**Comment by ubdbra001** [comment]
That would also be helpful! No rush though, I want to take my time and make sure that I'm not introducing any unintended side effects elsewhere (especially the stuff for connecting to the Pis)

**Comment by twVolc** [comment]
I've just finished the [spreadsheet](https://docs.google.com/spreadsheets/d/1uyOQfupUoy1YjrD_rg8sXmYE554euJpb/edit?usp=sharing&ouid=103131268621638531222&rtpof=true&sd=true) for information on processing_setting_defaults.txt. It's quite long-winded but hopefully it's useful. Let me know if anything doesn't make sense.

**Comment by twVolc** [comment]
> Starting to look at this issue, and spent yesterday creating an overview of where the different settings come from (in an excel sheet [here](https://docs.google.com/spreadsheets/d/1hwQofjTIiIAO1J0i_2rT4X0tUCwSM70TpzEp9MzsqRc/edit?usp=sharing)) in an attempt to make sure I know where changes will have an impact for each config file. @twVolc could you have a look and just make sure it looks roughly correct and that I haven't missed anything?

Also this looks good to me. There's definitely some parts you can totally ignore - like CameraSpecs, SpecSpecs, BasicAcqHandler, as these are pretty much completely to do with acquisitions (CameraSpecs and SpecSpecs will be updated automatically when connecting to an instrument, or defaults can be loaded through a text file - this is used on the Raspberry Pi so probably best to not mess with this at all for now). 

On the other hand, some features that are hard coded, such as the stray light and fit window for IFitWorker, would preferably be adjustable through the config file since these are settings that should be saved and subsequently be able to be reloaded  (they currently are saved in a text file after processing, but not in a format that the software can currently load back in - the user would just have to read the file and readjust the settings if they wanted to replicate that processing configuration).

**Comment by twVolc** [comment]
Yes that's a good point, a reference to that file that would automatically load up that time series as part of the configuration. That sounds like a good plan to me.

**Comment by ubdbra001** [comment]
I've been playing around with this a bit to try and work out what works best, and I think that loading the default config directly into `pyplis_worker` and then using that to add the defaults to the GUI is looking like the best option. That way these functions can be reused to update the config from another file and propogate these changes to the GUI (if required). Then the gather_vars functions for the different windows can be used to write to the config loaded in `pyplis_worker`.

What would be really useful is knowing whether the keys in the `process_settings.txt` files correspond directly to the attributes in `pyplis_worker`, i.e. can i just load the file and assign the keys and values as attributes? or are there some key-value pairs that require more processing?
If it's the latter it would be good if you could highlight them in the spreadsheet.

**Comment by twVolc** [comment]
> I've just finished the [spreadsheet](https://docs.google.com/spreadsheets/d/1uyOQfupUoy1YjrD_rg8sXmYE554euJpb/edit?usp=sharing&ouid=103131268621638531222&rtpof=true&sd=true) for information on processing_setting_defaults.txt. It's quite long-winded but hopefully it's useful. Let me know if anything doesn't make sense.

Sorry I can reply more when I'm back next week, but the spreadsheet here should give you the info you need on PyplisWorker/IFitWorker and the attributes that are associated with the processing_setting_defaults.txt keys. There's a column that states if it's PyplisWorker or IFiWorker, and if nothing else is stated then they have the same names as the key, otherwise the attribute name will be explicitly written down.

I tried to include information on how exactly the values are loaded in - e.g. some need to be passed to specific functions rather than written directly to PyplisWorker, to ensure they update all necessary things.

**Comment by ubdbra001** [comment]
Ah wonderful, I should have had a bit of a more thorough look at it. Thanks!

**Comment by ubdbra001** [comment]
No need to respond to this now (enjoy your leave), but for the places where the keys and attributes are different, can you see any reason why just changing the key name to match the attribute would have a negative impact?

**Comment by twVolc** [comment]
Sorry for being slow! Feel free to change things wherever necessary, or just ask me about specific ones and I can advise. I think for the most part the name differences are me being silly. For other cases it might be because `IFitWorker`and `PyplisWorker` have similar functions so need to be differentiated in the config file but have the same name as their attributes - e.g. the main one I can see for this is `use_light_dilution` and `use_light_dilution_spec `. In reality there's no reason why the IFitWorker attribute can't be changed to `use_light_dilution_spec`, at the time I just saw the "spec" part as obsolete as it's an attribute in IFitWorker so I already knew it was associated with the spectrometer.

I'm sure you know this, but just a note to say that if you do refactor things there may be cases where attributes are accessed with `get`/`set` functions, so just need to check that your IDE searches for and changes these instances too. although I suspect for the attributes that need changing this won't be the case.

**Comment by twVolc** [comment]
I'm just adding a column to the spreadsheet to note probably the most sensible new key/attribute name that can be shared by both. In some cases this will mean changing the key, in other cases the attribute. Let me know if this helps or doesn't make sense

**Comment by twVolc** [comment]
Sorry for the spamming of my thoughts - just realised in some cases it still isn't as easy and just changing the attribute/key name as sometimes you need to access dictionaries or use functions to properly load in a specific setting

**Comment by ubdbra001** [comment]
> Sorry for being slow! 

No problem, you were on leave and I made some progress on my own - I have a branch where `pyplis_worker` reads in the config file and the GUI pulls info from that. Still needs some work (e.g. changes to the GUI aren't reflected in the `pyplis_worker` config) but steps in the right direction.


> I'm just adding a column to the spreadsheet to note probably the most sensible new key/attribute name that can be shared by both. In some cases this will mean changing the key, in other cases the attribute. Let me know if this helps or doesn't make sense

V useful thanks!


> just realised in some cases it still isn't as easy and just changing the attribute/key name as sometimes you need to access dictionaries or use functions to properly load in a specific setting

This what what I was thinking may be the case, I saw you have added some info in the new spreadsheet column. Thanks!

**Comment by twVolc** [comment]
Just had a thought on how to potentially make things more straightforward for any attributes that aren't as simple as solely loading them in. Can we make them all properties in `PyplisWorker`, so that when we edit them the necessary function to perform all other requirements is within the property.setter function. E.g. see how `PyplisWorker.cell_cal_dir` works. Maybe this won't be possible for every key-attribute pair, but could be useful for some.

**Comment by ubdbra001** [comment]
Just to make sure I understand: So, when it comes to running the analysis I was thinking of having a function that loops through all the keys in the config dict within pyplis_worker and sets the values to attributes with the same name, and you're suggesting for the more complex keys (e.g. `cal_type_int`) we have a setter function that takes the value and does the extra stuff required?
If so, this is a much better idea than what I had as a plan.

The only issue I can think of is: how does this interect with what happens in the GUI code? Do we just remove this from the GUI code and let the seeting in `pyplis_worker` do all the work?

**Comment by ubdbra001** [comment]
Okay, great!
I'll have a play with doing this once I've got the easier config keys sorted. I'll focus on the ones that are vital to getting the config loading and saving working correctly first, and then have a think about what to do with ones like `PCS_lines` (which would be useful for no-GUI running, but work okay now)

**Comment by twVolc** [comment]
I guess I might be misinterpreting what the config dict is exactly. Are you suggesting `PyplisWorker` will read a new set of settings when you click "Run" so that the GUI needs to change the config dict each time rather than PyplisWorker settings directly (if config dict always overwrites these). I think this should be fine as long as loading in all settings isn't too slow - e.g. there might be times where we want to just change one setting, keeping all the rest the same, and then see the resulting change quickly (e.g. drawing a new PCS line and plotting it) - we don't really want to have to reload the whole set of settings to change this and see the change in the GUI. Really we just want to change that one line and see the new result. Will this be possible with you plan or will it always have to reload everything?

**Comment by ubdbra001** [comment]
I see what you mean, and I think your understanding is correct. When anything is run it will require setting the _all_ the attributes from the config dict.
I hadn't thought of this, but I don't anticipate this being expecially slow. Regardless I'll test it once it's done and see if it makes a substantial difference.
If it does then it may be possble to add something that allows for a partial update (possibly based on the dicts in the GUI components e.g. LightDilutionSettings com ein useful).

**Comment by twVolc** [comment]
Yeh that sounds good. Almost certainly something that can be navigated afterwards if we find issues, rather than worrying about it now. 

Some things (like the background model for instance) can be quite slow (probably <1 second so not the end of world but would make the GUI feel clunky for certain things), so are best only re-run when actually required.
