### ISSUE TITLE
Doesn't process first thirty minutes of data

### ISSUE THREAD

**Issue by tpering** [twVolc/PyCamPermanent#37]
As above, when processing data which starts at 00:00:00 the first 30 minutes are not plotted or added to the text file. This may or may not be related to the error below. Program throws an error when there is a large data gap (i.e., where a timezone puts two separate local days into a single UTC folder). 

![image](https://github.com/twVolc/PyCamPermanent/assets/7857899/5f87ab45-f58b-4422-b664-895dbfdbaf06)

**Comment by twVolc** [comment]
This might be a good time to check the Time Zone functionality. It definitely isn't perfect yet but could you try setting this to -11 and see if things process properly?

The bug will still need fixing, but this might at least mean you can get the data processed in the meantime.

**Comment by tpering** [comment]
For reference, identical error throws when using the Time Zone functionality.

**Comment by twVolc** [comment]
Possibly a different issue, but I think I'm also having issues with not all the data being saved. My `full_calibration.csv` file is missing the first 50 minutes and my emission rate files are missing the first 35 minutes of data for that same processing sequence. Possibly a buffer size issue if a large enough buffer hasn't been provided? When I process the data with my new mode - preloaded calibration, it saves all of the data. That makes me think it is to do with DOAS FOV calibration, since that takes a certain amount of images before it will run, then the earlier images are calibrated post-hoc - the buffer is used in this case.

**Comment by tpering** [comment]
I am closing this issue as the new updates seem to have solved the problem with processing of data.
