### ISSUE TITLE
"Include Calibration Offset" is not saved when ticking "Set as defaults" in the Doas-Calibration window

### ISSUE THREAD

**Issue by tpering** [twVolc/PyCamPermanent#41]
as above, when reloading software, this is unticked when previously it was ticked (maybe this is intended?)

**Comment by twVolc** [comment]
Looks like `processing_setting_defaults.txt` needs the flag `doas_cal_adjust_offset=1` added to it. for neatness mine is under the `# DOAS calibration and DOAS-AA calibration` section. My updates to this file are a mess to put into git because I have so many edits from processing different data (this links to #18). @ubdbra001 I wonder if you can add this update to the `processing_setting_defaults.txt`  file and push this update? Your version of that file might be less corrupted than mine. I'm sure there's a way I can do this without losing my current settings, but i'm just weary of messing things up.

**Comment by twVolc** [comment]
I think maybe if the flag doesn't already exist in `processing_setting_defaults.txt` , it won't be written into the file on saving defaults (this might be a bit of a bug in itself...)

**Comment by ubdbra001** [comment]
Noticed this in current work on config files. Should be fixed in PR #65
